### ISSUE TITLE
Attempting to use a c compiler in a OneDrive directory fails.

### ISSUE THREAD

**Issue by zoomiti** [jstaf/onedriver#175]
When attempting to use a c compiler within a OneDrive folder the linker program ld fails with a strange error message: Software caused connection abort. It seemed likely OneDriver was the culprit given that ld doesn't make connections to the internet.

``` console
$ make
gcc -pg -Wall -g -O0 -std=c99  -o main main.c
/usr/bin/ld: final link failed: Software caused connection abort
collect2: error: ld returned 1 exit status
$ ls
ls: cannot open directory '.': Transport endpoint is not connected
Transport endpoint is not connected (os error 107)
```

CDing away from and then back to a OneDrive directory fixes the transport endpoint issue.

**Comment by jstaf** [comment]
Yeah, when you see that it indicates the filesystem crashed somehow. `fusermount -uz MOUNTPOINT` to unmount it (or unmount/remount via the GUI). If you have any logs for the crash, please attach them here - they will usually point to what went wrong for errors like this one.

**Comment by Zjl37** [comment]
Hi there. I ran into the same problem when I invoked a C++ compiler. Here's what I did:

```
$ cd ~
$ mkdir 1drv
$ onedriver 1drv -d -l trace
```

```
$ cd ~/1drv/OIer
$ g++ XPfood.cpp -o XPfood
/usr/bin/ld: 最后的链结失败: 由软件导致的连接断开
collect2: error: ld returned 1 exit status
```

And here's the relevant output from onedriver, hope it is useful:

<details>

    2021/10/02 21:18:29 tx 680:     OK
    2021/10/02 21:18:29 rx 682: RELEASE i9223372036854775826 {Fh 0 0x8000  L0} 
    2021/10/02 21:18:29 tx 682:     OK
    2021/10/02 21:18:46 rx 684: GETATTR i1 {Fh 0} 
    TRAC[2021-10-02T21:18:46]inode.go:501 000061:fs.(*Inode).Getattr()                                               id="7E3F842765703161!103" path=/
    2021/10/02 21:18:46 tx 684:     OK, {tA=1s {M040755 SZ=4096 L=16 1000:1000 B8*4096 i0:1 A 1633178573.000000 M 1633178573.000000 C 1633178573.000000}}
    2021/10/02 21:18:46 rx 686: LOOKUP i1 ["OIer"] 5b
    TRAC[2021-10-02T21:18:46]inode.go:250 000029:fs.(*Inode).Lookup()                                               id="7E3F842765703161!103" name=OIer path=/
    2021/10/02 21:18:46 tx 686:     OK, {i9223372036854775813 g0 tE=1s tA=1s {M040755 SZ=4096 L=2 1000:1000 B8*4096 i0:9223372036854775813 A 1633176298.000000 M 1633176298.000000 C 1633176298.000000}}
    2021/10/02 21:18:46 rx 688: ACCESS i9223372036854775813 {u=1000 g=1000 x} 
    TRAC[2021-10-02T21:18:46]inode.go:501 000032:fs.(*Inode).Getattr()                                               id="7E3F842765703161!2220" path=/OIer
    2021/10/02 21:18:46 tx 688:     OK
    DEBU[2021-10-02T21:18:58]delta.go:21 000051:fs.(*Cache).DeltaLoop() Fetching deltas from server.                 
    2021/10/02 21:18:58 rx 690: LOOKUP i9223372036854775813 ["XPfood.cpp"] 11b
    TRAC[2021-10-02T21:18:58]inode.go:250 000061:fs.(*Inode).Lookup()                                               id="7E3F842765703161!2220" name=XPfood.cpp path=/OIer
    INFO[2021-10-02T21:18:58]oauth2.go:89 000051:fs/graph.(*Auth).Refresh() Auth tokens expired, attempting renewal.     
    INFO[2021-10-02T21:18:59]oauth2.go:89 000061:fs/graph.(*Auth).Refresh() Auth tokens expired, attempting renewal.     
    INFO[2021-10-02T21:18:59]delta.go:44 000051:fs.(*Cache).DeltaLoop() Fetched 0 deltas.                            
    DEBU[2021-10-02T21:18:59]cache.go:525 000051:fs.(*Cache).SerializeAll() Serializing cache metadata to disk.          
    2021/10/02 21:19:03 tx 690:     OK, {i9223372036854775827 g0 tE=1s tA=1s {M0100644 SZ=1072 L=1 1000:1000 B8*4096 i0:9223372036854775827 A 1588226320.000000 M 1588226320.000000 C 1588226320.000000}}
    2021/10/02 21:19:03 rx 692: ACCESS i9223372036854775827 {u=1000 g=1000 } 
    TRAC[2021-10-02T21:19:03]inode.go:501 000029:fs.(*Inode).Getattr()                                               id="7E3F842765703161!2708" path=/OIer/XPfood.cpp
    2021/10/02 21:19:03 tx 692:     OK
    2021/10/02 21:19:03 rx 694: LOOKUP i1 ["OIer"] 5b
    TRAC[2021-10-02T21:19:03]inode.go:250 000032:fs.(*Inode).Lookup()                                               id="7E3F842765703161!103" name=OIer path=/
    2021/10/02 21:19:03 tx 694:     OK, {i9223372036854775813 g0 tE=1s tA=1s {M040755 SZ=4096 L=36 1000:1000 B8*4096 i0:9223372036854775813 A 1633176298.000000 M 1633176298.000000 C 1633176298.000000}}
    2021/10/02 21:19:03 rx 696: LOOKUP i9223372036854775813 ["XPfood"] 7b
    TRAC[2021-10-02T21:19:03]inode.go:250 000032:fs.(*Inode).Lookup()                                               id="7E3F842765703161!2220" name=XPfood path=/OIer
    2021/10/02 21:19:03 tx 696:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
    2021/10/02 21:19:03 rx 698: LOOKUP i9223372036854775813 ["XPfood.cpp.gch"] 15b
    TRAC[2021-10-02T21:19:03]inode.go:250 000029:fs.(*Inode).Lookup()                                               id="7E3F842765703161!2220" name=XPfood.cpp.gch path=/OIer
    2021/10/02 21:19:03 tx 698:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
    2021/10/02 21:19:03 rx 700: OPEN i9223372036854775827 {O_RDONLY,0x8000} 
    DEBU[2021-10-02T21:19:03]inode.go:809 000061:fs.(*Inode).Open() Opening file for I/O.                         id="7E3F842765703161!2708" path=/OIer/XPfood.cpp
    INFO[2021-10-02T21:19:03]inode.go:846 000061:fs.(*Inode).Open() Found content in cache.                       id="7E3F842765703161!2708" path=/OIer/XPfood.cpp
    2021/10/02 21:19:03 tx 700:     OK, {Fh 0 }
    2021/10/02 21:19:03 rx 702: READ i9223372036854775827 {Fh 0 [0 +4096)  L 0 RDONLY,0x8000} 
    TRAC[2021-10-02T21:19:03]inode.go:363 000032:fs.(*Inode).Read() Read file                                     bufsize=1072 file_size=1072 id="7E3F842765703161!2708" offset=0 original_bufsize=4096 path=/OIer/XPfood.cpp
    2021/10/02 21:19:03 tx 702:     OK,  1072b data "#include"...
    2021/10/02 21:19:03 rx 704: FLUSH i9223372036854775827 {Fh 0} 
    DEBU[2021-10-02T21:19:03]inode.go:464 000029:fs.(*Inode).Flush()                                               id="7E3F842765703161!2708" path=/OIer/XPfood.cpp
    DEBU[2021-10-02T21:19:03]inode.go:431 000029:fs.(*Inode).Fsync()                                               id="7E3F842765703161!2708" path=/OIer/XPfood.cpp
    2021/10/02 21:19:03 tx 704:     OK
    2021/10/02 21:19:03 rx 706: RELEASE i9223372036854775827 {Fh 0 0x8000  L0} 
    2021/10/02 21:19:03 tx 706:     OK
    2021/10/02 21:19:03 rx 708: GETATTR i9223372036854775827 {Fh 0} 
    TRAC[2021-10-02T21:19:03]inode.go:501 000032:fs.(*Inode).Getattr()                                               id="7E3F842765703161!2708" path=/OIer/XPfood.cpp
    2021/10/02 21:19:03 tx 708:     OK, {tA=1s {M0100644 SZ=1072 L=1 1000:1000 B8*4096 i0:9223372036854775827 A 1588226320.000000 M 1588226320.000000 C 1588226320.000000}}
    2021/10/02 21:19:06 rx 710: LOOKUP i9223372036854775813 ["XPfood"] 7b
    TRAC[2021-10-02T21:19:06]inode.go:250 000029:fs.(*Inode).Lookup()                                               id="7E3F842765703161!2220" name=XPfood path=/OIer
    2021/10/02 21:19:06 tx 710:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
    2021/10/02 21:19:06 rx 712: LOOKUP i9223372036854775813 ["XPfood"] 7b
    TRAC[2021-10-02T21:19:06]inode.go:250 000061:fs.(*Inode).Lookup()                                               id="7E3F842765703161!2220" name=XPfood path=/OIer
    2021/10/02 21:19:06 tx 712:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
    2021/10/02 21:19:06 rx 714: CREATE i9223372036854775813 {0100664 [TRUNC,RDWR,CREAT,0x8000] (02)} ["XPfood"] 7b
    DEBU[2021-10-02T21:19:06]inode.go:644 000032:fs.(*Inode).Create() Creating inode.                               childid=local-c2WD8F2qNfHK5a84jjJk id="7E3F842765703161!2220" mode=100664 name=XPfood path=/OIer
    2021/10/02 21:19:06 tx 714:     OK, {i9223372036854775828 g0 {M0100644 SZ=0 L=0 0:0 B0*4096 i0:9223372036854775828 A 0.000000 M 0.000000 C 0.000000} &{0 0 0}}
    2021/10/02 21:19:06 rx 716: LOOKUP i9223372036854775813 ["libgcc_s.so.1"] 14b
    TRAC[2021-10-02T21:19:06]inode.go:250 000029:fs.(*Inode).Lookup()                                               id="7E3F842765703161!2220" name=libgcc_s.so.1 path=/OIer
    2021/10/02 21:19:06 tx 716:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
    2021/10/02 21:19:06 rx 718: LOOKUP i9223372036854775813 ["libgcc_s.so.1"] 14b
    TRAC[2021-10-02T21:19:06]inode.go:250 000061:fs.(*Inode).Lookup()                                               id="7E3F842765703161!2220" name=libgcc_s.so.1 path=/OIer
    2021/10/02 21:19:06 tx 718:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
    2021/10/02 21:19:06 rx 720: LOOKUP i9223372036854775813 ["libgcc_s.so.1"] 14b
    TRAC[2021-10-02T21:19:06]inode.go:250 000032:fs.(*Inode).Lookup()                                               id="7E3F842765703161!2220" name=libgcc_s.so.1 path=/OIer
    2021/10/02 21:19:06 tx 720:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
    2021/10/02 21:19:06 rx 722: LOOKUP i9223372036854775813 ["libgcc_s.so.1"] 14b
    TRAC[2021-10-02T21:19:06]inode.go:250 000029:fs.(*Inode).Lookup()                                               id="7E3F842765703161!2220" name=libgcc_s.so.1 path=/OIer
    2021/10/02 21:19:06 tx 722:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
    2021/10/02 21:19:06 rx 724: READ i9223372036854775828 {Fh 0 [0 +4096)  L 0 RDWR,0x8000} 
    TRAC[2021-10-02T21:19:06]inode.go:363 000061:fs.(*Inode).Read() Read file                                     bufsize=0 file_size=0 id=local-c2WD8F2qNfHK5a84jjJk offset=0 original_bufsize=4096 path=/OIer/XPfood
    2021/10/02 21:19:06 tx 724:     OK
    2021/10/02 21:19:06 rx 726: GETXATTR i9223372036854775828 {sz 0} ["security.capability"] 20b
    2021/10/02 21:19:06 tx 726:     38=function not implemented
    2021/10/02 21:19:06 rx 728: WRITE i9223372036854775828 {Fh 0 [64 +728)  L 0 RDWR,0x8000}  728b
    TRAC[2021-10-02T21:19:06]inode.go:377 000029:fs.(*Inode).Write() Write file                                    bufsize=728 id=local-c2WD8F2qNfHK5a84jjJk offset=64 path=/OIer/XPfood
    panic: runtime error: slice bounds out of range [:64] with capacity 0

    goroutine 29 [running]:
    github.com/jstaf/onedriver/fs.(*Inode).Write(0xc000436000, 0x857d20, 0xc0001b37c0, 0x0, 0x0, 0xc00068e200, 0x2d8, 0x10080, 0x40, 0x0, ...)
    	/usr/src/packages/BUILD/fs/inode.go:391 +0x819
    github.com/hanwen/go-fuse/v2/fs.(*rawBridge).Write(0xc0001d6240, 0xc000022600, 0xc00068e1b0, 0xc00068e200, 0x2d8, 0x10080, 0x0)
    	/usr/src/packages/BUILD/vendor/github.com/hanwen/go-fuse/v2/fs/bridge.go:785 +0x158
    github.com/hanwen/go-fuse/v2/fuse.doWrite(0xc0001fc000, 0xc00018c6c0)
    	/usr/src/packages/BUILD/vendor/github.com/hanwen/go-fuse/v2/fuse/opcode.go:191 +0x6d
    github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc0001fc000, 0xc00018c6c0, 0xc000000000)
    	/usr/src/packages/BUILD/vendor/github.com/hanwen/go-fuse/v2/fuse/server.go:468 +0x2b3
    github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc0001fc000, 0xc00024c701)
    	/usr/src/packages/BUILD/vendor/github.com/hanwen/go-fuse/v2/fuse/server.go:441 +0x196
    created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest
    	/usr/src/packages/BUILD/vendor/github.com/hanwen/go-fuse/v2/fuse/server.go:308 +0x42b

</details>
