### ISSUE TITLE
Panic occurs after suspension/hibernate

### ISSUE THREAD

**Issue by ChronicAdrift** [jstaf/onedriver#181]
Similar issue to #111.

```
$ onedriver --version
onedriver v0.11.1 32fd60e5
```
I saw no diffs to v0.11.2 that I thought would change the behaviour, but I have not looked into GO-FUSE.

```
Oct 22 09:28:01 $HOSTNAME onedriver[3402]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 22 09:28:01 $HOSTNAME onedriver[3402]: [signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x529007]
Oct 22 09:28:01 $HOSTNAME onedriver[3402]: goroutine 72 [running]:
Oct 22 09:28:01 $HOSTNAME onedriver[3402]: github.com/hanwen/go-fuse/v2/fs.(*rawBridge).logf(...)
Oct 22 09:28:01 $HOSTNAME onedriver[3402]:         /build/onedriver-PDB0UE/onedriver-0.11.1/vendor/github.com/hanwen/go-fuse/v2/fs/bridge.go:133
Oct 22 09:28:01 $HOSTNAME onedriver[3402]: github.com/hanwen/go-fuse/v2/fs.(*Inode).Path(0xc001168b40, 0xc001168000, 0x1, 0x0)
Oct 22 09:28:01 $HOSTNAME onedriver[3402]:         /build/onedriver-PDB0UE/onedriver-0.11.1/vendor/github.com/hanwen/go-fuse/v2/fs/inode.go:306 +0x447
Oct 22 09:28:01 $HOSTNAME onedriver[3402]: github.com/jstaf/onedriver/fs.(*Cache).InodePath(0xc000108080, 0xc001168b40, 0xc000156520, 0x4466ec)
Oct 22 09:28:01 $HOSTNAME onedriver[3402]:         /build/onedriver-PDB0UE/onedriver-0.11.1/fs/cache.go:140 +0x67
Oct 22 09:28:01 $HOSTNAME onedriver[3402]: github.com/jstaf/onedriver/fs.(*Inode).Rename(0xc001168b40, 0x857b80, 0xc0000a4030, 0xc000da2740, 0x1d, 0x854080, 0xc001168b40, 0xc0010582d0, 0xb, 0x0, ...)
Oct 22 09:28:01 $HOSTNAME onedriver[3402]:         /build/onedriver-PDB0UE/onedriver-0.11.1/fs/inode.go:719 +0x68
Oct 22 09:28:01 $HOSTNAME onedriver[3402]: github.com/jstaf/onedriver/fs.(*Cache).applyDelta(0xc000108080, 0xc001168a00, 0x0, 0x0)
Oct 22 09:28:01 $HOSTNAME onedriver[3402]:         /build/onedriver-PDB0UE/onedriver-0.11.1/fs/delta.go:231 +0x155a
Oct 22 09:28:01 $HOSTNAME onedriver[3402]: github.com/jstaf/onedriver/fs.(*Cache).DeltaLoop(0xc000108080, 0x6fc23ac00)
Oct 22 09:28:01 $HOSTNAME onedriver[3402]:         /build/onedriver-PDB0UE/onedriver-0.11.1/fs/delta.go:53 +0x2e9
Oct 22 09:28:01 $HOSTNAME onedriver[3402]: created by main.main
Oct 22 09:28:01 $HOSTNAME onedriver[3402]:         /build/onedriver-PDB0UE/onedriver-0.11.1/main.go:119 +0x7bc
```

I am going to update to v0.11.2 now and will tell when it reoccurs.
Also, thank you so much for your time and effort on this project!

**Comment by ChronicAdrift** [comment]
Seems to work very fine for now, closing. Thanks!
