### ISSUE TITLE
GUI auth popup won't display

### ISSUE THREAD

**Issue by ajbucci** [jstaf/onedriver#271]
I'm on arch/gnome/wayland/nvidia proprietary drivers with latest onedriver built from source. 

My current workaround is to use the CLI with the -n option (which works).

Here's the log:

> Aug 07 15:55:21 DESKTOP-ARCH systemd[88699]: Started onedriver.
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: 15:55:21 INF onedriver v0.12.0 f00fbb1d
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: fatal error: unexpected signal during runtime execution
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7f2888030d74]
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime stack:
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.throw({0x750acd?, 0x3500000021?})
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/panic.go:1047 +0x5d fp=0x7fff96283f18 sp=0x7fff96283ee8 pc=0x43841d
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.sigpanic()
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/signal_unix.go:819 +0x369 fp=0x7fff96283f68 sp=0x7fff96283f18 pc=0x44e0a9
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: goroutine 1 [syscall]:
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.cgocall(0x6ba530, 0xc0001439a8)
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/cgocall.go:158 +0x5c fp=0xc000143980 sp=0xc000143948 pc=0x406cfc
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: github.com/jstaf/onedriver/fs/graph._Cfunc_webkit_auth_window(0x29cfe60, 0x29cff60)
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         _cgo_gotypes.go:127 +0x4d fp=0xc0001439a8 sp=0xc000143980 pc=0x68ba8d
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: github.com/jstaf/onedriver/fs/graph.getAuthCode({0x0, 0x0})
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /home/aj/onedriver/fs/graph/oauth2_gtk.go:23 +0xd4 fp=0xc000143a48 sp=0xc0001439a8 pc=0x68bc74
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: github.com/jstaf/onedriver/fs/graph.newAuth({0xc000024140, 0x3b}, 0x0)
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /home/aj/onedriver/fs/graph/oauth2.go:205 +0x98 fp=0xc000143b18 sp=0xc000143a48 pc=0x68b6d8
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: github.com/jstaf/onedriver/fs/graph.Authenticate({0xc000024140, 0x3b}, 0x68?)
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /home/aj/onedriver/fs/graph/oauth2.go:223 +0x85 fp=0xc000143b58 sp=0xc000143b18 pc=0x68b845
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: main.main()
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /home/aj/onedriver/cmd/onedriver/main.go:114 +0x905 fp=0xc000143f80 sp=0xc000143b58 pc=0x6b9ca5
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.main()
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/proc.go:250 +0x212 fp=0xc000143fe0 sp=0xc000143f80 pc=0x43ac72
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.goexit()
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000143fe8 sp=0xc000143fe0 pc=0x4686a1
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: goroutine 2 [force gc (idle)]:
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/proc.go:363 +0xd6 fp=0xc00004cfb0 sp=0xc00004cf90 pc=0x43b036
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.goparkunlock(...)
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/proc.go:369
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.forcegchelper()
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/proc.go:302 +0xad fp=0xc00004cfe0 sp=0xc00004cfb0 pc=0x43aecd
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.goexit()
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004cfe8 sp=0xc00004cfe0 pc=0x4686a1
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: created by runtime.init.6
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/proc.go:290 +0x25
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: goroutine 3 [GC sweep wait]:
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/proc.go:363 +0xd6 fp=0xc00004d790 sp=0xc00004d770 pc=0x43b036
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.goparkunlock(...)
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/proc.go:369
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.bgsweep(0x0?)
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc00004d7c8 sp=0xc00004d790 pc=0x427b2e
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.gcenable.func1()
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/mgc.go:178 +0x26 fp=0xc00004d7e0 sp=0xc00004d7c8 pc=0x41c9e6
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.goexit()
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004d7e8 sp=0xc00004d7e0 pc=0x4686a1
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: created by runtime.gcenable
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/mgc.go:178 +0x6b
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: goroutine 4 [GC scavenge wait]:
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.gopark(0xc000076000?, 0x7cb8d0?, 0x1?, 0x0?, 0x0?)
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/proc.go:363 +0xd6 fp=0xc00004df70 sp=0xc00004df50 pc=0x43b036
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.goparkunlock(...)
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/proc.go:369
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.(*scavengerState).park(0x99a860)
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc00004dfa0 sp=0xc00004df70 pc=0x425bd3
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.bgscavenge(0x0?)
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc00004dfc8 sp=0xc00004dfa0 pc=0x4261a5
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.gcenable.func2()
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/mgc.go:179 +0x26 fp=0xc00004dfe0 sp=0xc00004dfc8 pc=0x41c986
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.goexit()
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004dfe8 sp=0xc00004dfe0 pc=0x4686a1
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: created by runtime.gcenable
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/mgc.go:179 +0xaa
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: goroutine 5 [finalizer wait]:
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.gopark(0x99b1a0?, 0xc000007860?, 0x0?, 0x0?, 0xc00004c770?)
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/proc.go:363 +0xd6 fp=0xc00004c628 sp=0xc00004c608 pc=0x43b036
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.goparkunlock(...)
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/proc.go:369
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.runfinq()
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/mfinal.go:180 +0x10f fp=0xc00004c7e0 sp=0xc00004c628 pc=0x41baef
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: runtime.goexit()
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004c7e8 sp=0xc00004c7e0 pc=0x4686a1
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]: created by runtime.createfing
> Aug 07 15:55:21 DESKTOP-ARCH onedriver[99910]:         /usr/lib/go/src/runtime/mfinal.go:157 +0x45
> Aug 07 15:55:21 DESKTOP-ARCH systemd[88699]: onedriver@home-aj-OneDrive.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
> Aug 07 15:55:21 DESKTOP-ARCH fusermount[99963]: /usr/bin/fusermount: entry for /home/aj/OneDrive not found in /etc/mtab
> Aug 07 15:55:21 DESKTOP-ARCH systemd[88699]: onedriver@home-aj-OneDrive.service: Control process exited, code=exited, status=1/FAILURE
> Aug 07 15:55:21 DESKTOP-ARCH systemd[88699]: onedriver@home-aj-OneDrive.service: Failed with result 'exit-code'.
> Aug 07 15:55:24 DESKTOP-ARCH systemd[88699]: onedriver@home-aj-OneDrive.service: Scheduled restart job, restart counter is at 3.
> Aug 07 15:55:24 DESKTOP-ARCH systemd[88699]: Stopped onedriver.

**Comment by ajbucci** [comment]
Worked after a restart *shrug*
