### ISSUE TITLE
The login page cannot be displayed

### ISSUE THREAD

**Issue by Traveller-hongchen** [jstaf/onedriver#383]
After I selected the mount directory, there was no login window popping up

I'm using debian 12，linux-image-6.1.0-17-amd64

{"level":"warn","error":"open /home/hongchen/.config/onedriver/config.yml: no such file or directory","path":"/home/hongchen/.config/onedriver/config.yml","time":"2024-02-11T22:31:33+08:00","message":"Configuration file not found, using defaults."}
22:31:33 INF onedriver-launcher v0.14.1 15a1c642
22:31:37 INF Creating mountpoint. mountpoint=/home/hongchen/onedrive systemdUnit=onedriver@home-hongchen-onedrive.service
22:31:37 ERR Could not determine acccount name. error="open /home/hongchen/.cache/onedriver/home-hongchen-onedrive/auth_tokens.json: no such file or directory" mountpoint=/home/hongchen/onedrive
22:31:37 DBG Opening directory. dir=/home/hongchen/onedrive
22:33:38 ERR Either directory was invalid or exceeded timeout waiting for fs to become available. dir=/home/hongchen/onedrive

**Comment by alexmyczko** [comment]
I have packaged onedrive, and was not able to reproduce this. However I tried on Debian sid, not Debian 12.

Also try running the gui app from command line to see messages, instead of clicking the app icon.

If you want to give the package a try?

http://sid.ethz.ch/debian/onedriver/

**Comment by Traveller-hongchen** [comment]
I tried running the gui app from command line to see messages, The message is what I wrote above.
I'm working fine on another machine, so I'm not sure if there's something on my machine that's causing the issue.

New package still has this issue.

Thank you for your development

**Comment by acescos** [comment]
Hi,
I've encountered the same issue on MX Linux 23, which is built on Debian 12. Specifically, upon opening the GUI and selecting a folder for mount it, Onedriver fails to open the logging window. Strangely, I've successfully used the this software on another laptop with identical operating system but different hardware. Below are the details of the laptop experiencing the logging problem.

  Kernel: 6.1.0-17-amd64 [6.1.69-1] arch: x86_64 bits: 64 compiler: gcc v: 12.2.0
    parameters: BOOT_IMAGE=/vmlinuz-6.1.0-17-amd64 root=UUID=<filter> ro quiet splash
    resume=UUID=<filter> resume_offset=146794496
  Desktop: KDE Plasma v: 5.27.5 wm: kwin_x11 vt: 7 dm: SDDM Distro: MX-23.2_KDE_x64 Libretto
    January 21 2024 base: Debian GNU/Linux 12 (bookworm)


![imagen](https://github.com/jstaf/onedriver/assets/36568488/6bf4a4de-7cce-4446-867e-afa935ac1baf)


![Screenshot_20240220_233823](https://github.com/jstaf/onedriver/assets/36568488/5763d51c-a104-49cf-ad5b-ac3402592519)

**Comment by Traveller-hongchen** [comment]
> Hello,
> first i thank the developer for this cool kind of app.
> I have the same problem on Ubuntu 22.04.4 LTS.
> Some posts from my log:
> ```
> Feb 21 13:31:44 Z440 onedriver.desktop[52094]: 13:31:44 INF Creating mountpoint. mountpoint=/data/Onedriver systemdUnit=onedriver@data-Onedriver.service
> Feb 21 13:31:44 Z440 systemd[2529]: Created slice Slice /app/onedriver.
> Feb 21 13:31:44 Z440 onedriver.desktop[52094]: 13:31:44 ERR Could not determine acccount name. error="open /home/hansi/.cache/onedriver/data-Onedriver/auth_tokens.json: no such file or dire>
> Feb 21 13:31:44 Z440 systemd[2529]: Started onedriver.
> Feb 21 13:31:44 Z440 onedriver.desktop[52094]: 13:31:44 DBG Opening directory. dir=/data/Onedriver
> Feb 21 13:31:44 Z440 onedriver[52410]: 13:31:44 INF onedriver v0.14.1 15a1c642
> Feb 21 13:31:44 Z440 onedriver[52410]: Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
> Feb 21 13:31:45 Z440 onedriver[52450]: KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Keine Berechtigung
> Feb 21 13:31:45 Z440 onedriver[52450]: Failed to create GBM buffer of size 450x600: Keine Berechtigung
> Feb 21 13:31:45 Z440 onedriver[52450]: KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Keine Berechtigung
> Feb 21 13:31:45 Z440 onedriver[52450]: Failed to create GBM buffer of size 450x600: Keine Berechtigung
> Feb 21 13:31:45 Z440 onedriver[52450]: KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Keine Berechtigung
> Feb 21 13:31:45 Z440 onedriver[52450]: Failed to create GBM buffer of size 450x600: Keine Berechtigung
> Feb 21 13:31:45 Z440 onedriver[52450]: Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
> Feb 21 13:32:10 Z440 systemd[1]: systemd-hostnamed.service: Deactivated successfully.
> eb 21 13:33:39 Z440 onedriver[52410]: 13:33:39 FTL No validation code returned, or code was invalid. Please restart the application and try again.
> Feb 21 13:33:39 Z440 systemd[2529]: onedriver@data-Onedriver.service: Main process exited, code=exited, status=1/FAILURE
> Feb 21 13:33:39 Z440 fusermount[52712]: /usr/bin/fusermount: entry for /data/Onedriver not found in /etc/mtab
> Feb 21 13:33:39 Z440 systemd[2529]: onedriver@data-Onedriver.service: Control process exited, code=exited, status=1/FAILURE
> Feb 21 13:33:39 Z440 systemd[2529]: onedriver@data-Onedriver.service: Failed with result 'exit-code'.
> Feb 21 13:33:39 Z440 systemd[2529]: onedriver@data-Onedriver.service: Consumed 2.273s CPU time.
> ```

Hello, where did you get this journal? I am new to Linux and hope you can help me understand it

**Comment by sf-000** [comment]
> > Hello,
> > first i thank the developer for this cool kind of app.
> > I have the same problem on Ubuntu 22.04.4 LTS.
> > Some posts from my log:
> > ```
> > Feb 21 13:31:44 Z440 onedriver.desktop[52094]: 13:31:44 INF Creating mountpoint. mountpoint=/data/Onedriver systemdUnit=onedriver@data-Onedriver.service
> > Feb 21 13:31:44 Z440 systemd[2529]: Created slice Slice /app/onedriver.
> > Feb 21 13:31:44 Z440 onedriver.desktop[52094]: 13:31:44 ERR Could not determine acccount name. error="open /home/hansi/.cache/onedriver/data-Onedriver/auth_tokens.json: no such file or dire>
> > Feb 21 13:31:44 Z440 systemd[2529]: Started onedriver.
> > Feb 21 13:31:44 Z440 onedriver.desktop[52094]: 13:31:44 DBG Opening directory. dir=/data/Onedriver
> > Feb 21 13:31:44 Z440 onedriver[52410]: 13:31:44 INF onedriver v0.14.1 15a1c642
> > Feb 21 13:31:44 Z440 onedriver[52410]: Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
> > Feb 21 13:31:45 Z440 onedriver[52450]: KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Keine Berechtigung
> > Feb 21 13:31:45 Z440 onedriver[52450]: Failed to create GBM buffer of size 450x600: Keine Berechtigung
> > Feb 21 13:31:45 Z440 onedriver[52450]: KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Keine Berechtigung
> > Feb 21 13:31:45 Z440 onedriver[52450]: Failed to create GBM buffer of size 450x600: Keine Berechtigung
> > Feb 21 13:31:45 Z440 onedriver[52450]: KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Keine Berechtigung
> > Feb 21 13:31:45 Z440 onedriver[52450]: Failed to create GBM buffer of size 450x600: Keine Berechtigung
> > Feb 21 13:31:45 Z440 onedriver[52450]: Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
> > Feb 21 13:32:10 Z440 systemd[1]: systemd-hostnamed.service: Deactivated successfully.
> > eb 21 13:33:39 Z440 onedriver[52410]: 13:33:39 FTL No validation code returned, or code was invalid. Please restart the application and try again.
> > Feb 21 13:33:39 Z440 systemd[2529]: onedriver@data-Onedriver.service: Main process exited, code=exited, status=1/FAILURE
> > Feb 21 13:33:39 Z440 fusermount[52712]: /usr/bin/fusermount: entry for /data/Onedriver not found in /etc/mtab
> > Feb 21 13:33:39 Z440 systemd[2529]: onedriver@data-Onedriver.service: Control process exited, code=exited, status=1/FAILURE
> > Feb 21 13:33:39 Z440 systemd[2529]: onedriver@data-Onedriver.service: Failed with result 'exit-code'.
> > Feb 21 13:33:39 Z440 systemd[2529]: onedriver@data-Onedriver.service: Consumed 2.273s CPU time.
> > ```
> 
> Hello, where did you get this journal? I am new to Linux and hope you can help me understand it

On the console with:
`journalctl `
or 
`journalctl -n 200`
better
`journalctl -n200`
makber even better for you quickly find onedrive logs
`journalctl -b | grep onedriver`
On Linux Systems with systemd
-b = logs since Boot
-n = is showing lines

**Comment by Traveller-hongchen** [comment]
I tried to use the "journalctl" command to get the logs, and when I pressed select the directory, the logs looked like this
`2月 22 19:42:58 hongchen systemd[1277]: Started onedriver@home-hongchen-test.service - onedriver.
2月 22 19:42:58 hongchen onedriver[6575]: 19:42:58 INF onedriver v0.14.1 15a1c642
2月 22 19:42:58 hongchen onedriver[6575]: Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
2月 22 19:42:58 hongchen onedriver[6575]: EGLDisplay Initialization failed: EGL_NOT_INITIALIZED
2月 22 19:42:58 hongchen onedriver[6575]: Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
2月 22 19:42:58 hongchen onedriver[6575]: fatal error: unexpected signal during runtime execution
2月 22 19:42:58 hongchen onedriver[6575]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7fb0e406f6eb]
2月 22 19:42:58 hongchen onedriver[6575]: runtime stack:
2月 22 19:42:58 hongchen onedriver[6575]: runtime.throw({0x8e397f?, 0x7fb0d948a19f?})
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/panic.go:1047 +0x5d fp=0x7ffde5e4c470 sp=0x7ffde5e4c440 pc=0x4b865d
2月 22 19:42:58 hongchen onedriver[6575]: runtime.sigpanic()
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/signal_unix.go:819 +0x369 fp=0x7ffde5e4c4c0 sp=0x7ffde5e4c470 pc=0x4ce309
2月 22 19:42:58 hongchen onedriver[6575]: goroutine 1 [syscall]:
2月 22 19:42:58 hongchen onedriver[6575]: runtime.cgocall(0x7988d0, 0xc0001e37a0)
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/cgocall.go:158 +0x5c fp=0xc0001e3778 sp=0xc0001e3740 pc=0x486c3c
2月 22 19:42:58 hongchen onedriver[6575]: github.com/jstaf/onedriver/fs/graph._Cfunc_webkit_auth_window(0x2460de0, 0x246f010)
2月 22 19:42:58 hongchen onedriver[6575]:         _cgo_gotypes.go:127 +0x4d fp=0xc0001e37a0 sp=0xc0001e3778 pc=0x71716d
2月 22 19:42:58 hongchen onedriver[6575]: github.com/jstaf/onedriver/fs/graph.getAuthCode({{0x8e08fd, 0x24}, {0x8e8b56, 0x3e}, {0x8e8233, 0x3a}, {0x8e36df, 0x2a}}, {0x0, 0x0})
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/src/packages/BUILD/fs/graph/oauth2_gtk.go:24 +0x1f1 fp=0xc0001e38c8 sp=0xc0001e37a0 pc=0x717471
2月 22 19:42:58 hongchen onedriver[6575]: github.com/jstaf/onedriver/fs/graph.newAuth({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, {0xc0001da320, 0x43}, ...)
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/src/packages/BUILD/fs/graph/oauth2.go:232 +0x26c fp=0xc0001e3a60 sp=0xc0001e38c8 pc=0x716c4c
2月 22 19:42:58 hongchen onedriver[6575]: github.com/jstaf/onedriver/fs/graph.Authenticate({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, {0xc0001da320, 0x43}, ...)
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/src/packages/BUILD/fs/graph/oauth2.go:251 +0x10c fp=0xc0001e3ad8 sp=0xc0001e3a60 pc=0x716ecc
2月 22 19:42:58 hongchen onedriver[6575]: main.main()
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/src/packages/BUILD/cmd/onedriver/main.go:127 +0xb19 fp=0xc0001e3f80 sp=0xc0001e3ad8 pc=0x798019
2月 22 19:42:58 hongchen onedriver[6575]: runtime.main()
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/proc.go:250 +0x212 fp=0xc0001e3fe0 sp=0xc0001e3f80 pc=0x4baeb2
2月 22 19:42:58 hongchen onedriver[6575]: runtime.goexit()
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0001e3fe8 sp=0xc0001e3fe0 pc=0x4e8a61
2月 22 19:42:58 hongchen onedriver[6575]: goroutine 2 [force gc (idle)]:
2月 22 19:42:58 hongchen onedriver[6575]: runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/proc.go:363 +0xd6 fp=0xc000056fb0 sp=0xc000056f90 pc=0x4bb276
2月 22 19:42:58 hongchen onedriver[6575]: runtime.goparkunlock(...)
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/proc.go:369
2月 22 19:42:58 hongchen onedriver[6575]: runtime.forcegchelper()
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/proc.go:302 +0xad fp=0xc000056fe0 sp=0xc000056fb0 pc=0x4bb10d
2月 22 19:42:58 hongchen onedriver[6575]: runtime.goexit()
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000056fe8 sp=0xc000056fe0 pc=0x4e8a61
2月 22 19:42:58 hongchen onedriver[6575]: created by runtime.init.6
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/proc.go:290 +0x25
2月 22 19:42:58 hongchen onedriver[6575]: goroutine 3 [GC sweep wait]:
2月 22 19:42:58 hongchen onedriver[6575]: runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/proc.go:363 +0xd6 fp=0xc000057790 sp=0xc000057770 pc=0x4bb276
2月 22 19:42:58 hongchen onedriver[6575]: runtime.goparkunlock(...)
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/proc.go:369
2月 22 19:42:58 hongchen onedriver[6575]: runtime.bgsweep(0x0?)
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/mgcsweep.go:278 +0x8e fp=0xc0000577c8 sp=0xc000057790 pc=0x4a7c6e
2月 22 19:42:58 hongchen onedriver[6575]: runtime.gcenable.func1()
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/mgc.go:178 +0x26 fp=0xc0000577e0 sp=0xc0000577c8 pc=0x49c926
2月 22 19:42:58 hongchen onedriver[6575]: runtime.goexit()
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000577e8 sp=0xc0000577e0 pc=0x4e8a61
2月 22 19:42:58 hongchen onedriver[6575]: created by runtime.gcenable
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/mgc.go:178 +0x6b
2月 22 19:42:58 hongchen onedriver[6575]: goroutine 4 [GC scavenge wait]:
2月 22 19:42:58 hongchen onedriver[6575]: runtime.gopark(0xc00007e000?, 0x9687c8?, 0x1?, 0x0?, 0x0?)
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/proc.go:363 +0xd6 fp=0xc000057f70 sp=0xc000057f50 pc=0x4bb276
2月 22 19:42:58 hongchen onedriver[6575]: runtime.goparkunlock(...)
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/proc.go:369
2月 22 19:42:58 hongchen onedriver[6575]: runtime.(*scavengerState).park(0xba6880)
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc000057fa0 sp=0xc000057f70 pc=0x4a5d13
2月 22 19:42:58 hongchen onedriver[6575]: runtime.bgscavenge(0x0?)
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc000057fc8 sp=0xc000057fa0 pc=0x4a62e5
2月 22 19:42:58 hongchen onedriver[6575]: runtime.gcenable.func2()
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/mgc.go:179 +0x26 fp=0xc000057fe0 sp=0xc000057fc8 pc=0x49c8c6
2月 22 19:42:58 hongchen onedriver[6575]: runtime.goexit()
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000057fe8 sp=0xc000057fe0 pc=0x4e8a61
2月 22 19:42:58 hongchen onedriver[6575]: created by runtime.gcenable
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/mgc.go:179 +0xaa
2月 22 19:42:58 hongchen onedriver[6575]: goroutine 18 [finalizer wait]:
2月 22 19:42:58 hongchen onedriver[6575]: runtime.gopark(0xba71c0?, 0xc0001861a0?, 0x0?, 0x0?, 0xc000056770?)
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/proc.go:363 +0xd6 fp=0xc000056628 sp=0xc000056608 pc=0x4bb276
2月 22 19:42:58 hongchen onedriver[6575]: runtime.goparkunlock(...)
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/proc.go:369
2月 22 19:42:58 hongchen onedriver[6575]: runtime.runfinq()
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/mfinal.go:180 +0x10f fp=0xc0000567e0 sp=0xc000056628 pc=0x49ba2f
2月 22 19:42:58 hongchen onedriver[6575]: runtime.goexit()
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000567e8 sp=0xc0000567e0 pc=0x4e8a61
2月 22 19:42:58 hongchen onedriver[6575]: created by runtime.createfing
2月 22 19:42:58 hongchen onedriver[6575]:         /usr/lib/go-1.19/src/runtime/mfinal.go:157 +0x45
2月 22 19:42:58 hongchen systemd[1277]: onedriver@home-hongchen-test.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
2月 22 19:42:58 hongchen systemd[1277]: onedriver@home-hongchen-test.service: Control process exited, code=exited, status=1/FAILURE
2月 22 19:42:58 hongchen systemd[1277]: onedriver@home-hongchen-test.service: Failed with result 'exit-code'.`

Maybe that's the key message?

`2月 22 19:42:58 hongchen onedriver[6575]: Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
2月 22 19:42:58 hongchen onedriver[6575]: EGLDisplay Initialization failed: EGL_NOT_INITIALIZED
2月 22 19:42:58 hongchen onedriver[6575]: Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
2月 22 19:42:58 hongchen onedriver[6575]: fatal error: unexpected signal during runtime execution
2月 22 19:42:58 hongchen onedriver[6575]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7fb0e406f6eb]
2月 22 19:42:58 hongchen onedriver[6575]: runtime stack:
2月 22 19:42:58 hongchen onedriver[6575]: runtime.throw({0x8e397f?, 0x7fb0d948a19f?})`

**Comment by Traveller-hongchen** [comment]
> does you use this: `journalctl -b | grep onedriver`  ?

i used journalctl -f | grep onedriver

**Comment by sf-000** [comment]
> I have packaged onedrive, and was not able to reproduce this. However I tried on Debian sid, not Debian 12.
> 
> Also try running the gui app from command line to see messages, instead of clicking the app icon.
> 
> If you want to give the package a try?
> 
> http://sid.ethz.ch/debian/onedriver/

I have error with this package:
```
hansi@Z440:~$ sudo dpkg -i '/home/hansi/Downloads/onedriver_0.14.1-1_amd64 (1).deb' 
Vormals nicht ausgewähltes Paket onedriver wird gewählt.
(Lese Datenbank ... 210880 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../onedriver_0.14.1-1_amd64 (1).deb ...
Entpacken von onedriver (0.14.1-1) ...
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von onedriver:
 onedriver hängt ab von libwebkit2gtk-4.1-0 (>= 2.5.3); aber:
  Paket libwebkit2gtk-4.1-0 ist nicht installiert.

dpkg: Fehler beim Bearbeiten des Paketes onedriver (--install):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Trigger für mailcap (3.70+nmu1ubuntu1) werden verarbeitet ...
Trigger für gnome-menus (3.36.0-1ubuntu3) werden verarbeitet ...
Trigger für desktop-file-utils (0.26-1ubuntu3) werden verarbeitet ...
Trigger für man-db (2.10.2-1) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 onedriver
```

**Comment by JohnGalt1717** [comment]
I'm getting the same on fedora 39, and installing webket2gtk-4 doesn't appear to solve it. Any ideas?

**Comment by acescos** [comment]
I resolved the issue by transitioning from MX Linux's default SysVinit to Systemd as the init and service manager. I acknowledge that this solution may seem somewhat crude.

**Comment by alexmyczko** [comment]
@sf-000 try not `dpkg -i` but `apt install ./the.deb`

**Comment by deiussum** [comment]
I am running into a similar issue with a fresh Endeavor OS install running KDE Plasma (6.1.4)  Kernel version is 6.10.7-arch1 (64-bit)

The error I'm getting that I think is the culprit is this:

`Error 71 (Protocol error) dispatching to Wayland display.`

**Comment by eudesjuniorr** [comment]
Hey guys. After a long time, I finally managed to solve that problem. Here's how I did it: 

1. On the terminal, run OneDriver with the `--no-browser` flag to avoid any browser issues. This will give you a URL that you can open manually to authenticate: `onedriver --no-browser ~/Documents`
Replace `~/Documents` with your desired mount point.
2. Copy the provided URL from the terminal and open it in your browser. After logging in, you'll be redirected to a blank page.
3. Copy the full URL from that blank page and paste it back into the terminal where OneDriver is waiting.

Additionally, if you encounter permission issues or errors related to missing configuration files, you may need to run the following commands to ensure correct ownership of OneDriver's config/cache directories: `mkdir -p ~/.config/onedriver ~/.cache/onedriver`

Feel free to modify or adjust it as needed

**Comment by mindgam3s** [comment]
> Hey guys. After a long time, I finally managed to solve that problem. Here's how I did it:
> 
>     1. On the terminal, run OneDriver with the `--no-browser` flag to avoid any browser issues. This will give you a URL that you can open manually to authenticate: `onedriver --no-browser ~/Documents`
>        Replace `~/Documents` with your desired mount point.
> 
>     2. Copy the provided URL from the terminal and open it in your browser. After logging in, you'll be redirected to a blank page.
> 
>     3. Copy the full URL from that blank page and paste it back into the terminal where OneDriver is waiting.
> 
> 
> Additionally, if you encounter permission issues or errors related to missing configuration files, you may need to run the following commands to ensure correct ownership of OneDriver's config/cache directories: `mkdir -p ~/.config/onedriver ~/.cache/onedriver`
> 
> Feel free to modify or adjust it as needed

thank you so much! this solved it!

**Comment by Dollique** [comment]
If the `-n` or `--no-browser` flag does not work, you can also use this:
```
WEBKIT_DISABLE_DMABUF_RENDERER=1 onedriver ~/path/to/mount/
```
And make sure you cleaned your cache like described [above](https://github.com/jstaf/onedriver/issues/383#issuecomment-2332164277).
```
mkdir -p ~/.config/onedriver ~/.cache/onedriver 
```
