### ISSUE TITLE
Fix segfault in delta thread

### ISSUE THREAD

**Issue by jstaf** [jstaf/onedriver#93]
While moving ~20 files, the delta thread ran into a nil pointer (I think the file was already moved and the delta thread couldn't find it somehow?):

```
Aug 09 22:45:19 onedriver[71477]: time="2020-08-09T22:45:19" level=info msg="Skipping, no changes relative to local state." func="000069:fs.(*Cache).applyDelta()" file="delta.go:257" delta=skip id="different_file" name=different_file
Aug 09 22:45:19 onedriver[71477]: time="2020-08-09T22:45:19" level=debug msg="Applying delta" func="000069:fs.(*Cache).applyDelta()" file="delta.go:131" id="removed" name="removed"
Aug 09 22:45:19 onedriver[71477]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 09 22:45:19 onedriver[71477]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6e25ef]
Aug 09 22:45:19 onedriver[71477]: goroutine 69 [running]:
Aug 09 22:45:19 onedriver[71477]: github.com/jstaf/onedriver/fs.(*Cache).applyDelta(0xc0000ec000, 0xc003d588c0, 0x0, 0x0)
Aug 09 22:45:19 onedriver[71477]:         /builddir/build/BUILD/onedriver-0.9.1/fs/delta.go:226 +0xa8f
Aug 09 22:45:19 onedriver[71477]: github.com/jstaf/onedriver/fs.(*Cache).DeltaLoop(0xc0000ec000, 0x6fc23ac00)
Aug 09 22:45:19 onedriver[71477]:         /builddir/build/BUILD/onedriver-0.9.1/fs/delta.go:53 +0x2e9
Aug 09 22:45:19 onedriver[71477]: created by main.main
Aug 09 22:45:19 onedriver[71477]:         /builddir/build/BUILD/onedriver-0.9.1/cmd/onedriver/main.go:119 +0x7bc
Aug 09 22:45:19 systemd[1960]: onedriver@home-jstaf-OneDrive.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by jstaf** [comment]
I think this is a duplicate of #111 (fixed in latest version), going to close this one.
